uaa-base-url: http://localhost:8080/uaa

server:
  port: 9999

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${uaa-base-url}/token_keys



#security:
#  basic:
#  oauth2:
#    client:
#      client-id: resource1
#      client-secret: resource1
#      grant-type: client_credentials
#      scope:
#        - resource.read
#        - resource.write
#      access-token-uri: ${ssoServiceUrl}/oauth/token
#      user-authorization-uri: ${ssoServiceUrl}/oauth/authorize
#    resource:
#      token-info-uri: ${ssoServiceUrl}/oauth/check_token
#      jwt:
#        key-uri: ${ssoServiceUrl}/token_key
#      user-info-uri: ${ssoServiceUrl}/userinfo
#      id: resource

logging.level:
  org.springframework.security: DEBUG